import streamlit as st

# Page Configuration
st.set_page_config(
    page_title="Disclaimer - Tenant-Landlord Legal AI Suite",
    page_icon="⚖️",
    layout="wide",
)

# Title and Introduction
st.title("⚖️ Disclaimer")
st.subheader("Important Legal Information")
st.markdown(
    """
    **Please read this disclaimer carefully before using the Tenant-Landlord Legal AI Suite.** 
    By accessing or using this application, you agree to the terms outlined below.
    """
)

# General Disclaimer
st.header("📄 General Disclaimer")
st.markdown(
    """
    - The **Tenant-Landlord Legal AI Suite** is an AI-powered tool designed to assist users in understanding legal options and analyzing data related to tenant-landlord disputes. 
    - This application does **not provide legal advice** and should not be relied upon as a substitute for consultation with a qualified attorney licensed to practice in your jurisdiction.
    - While we strive for accuracy, the information and outputs provided by the application may not reflect the most recent legal developments or local laws. Use at your own risk.
    """
)

# Jurisdictional Disclaimer
st.header("🌎 Jurisdictional Disclaimer")
st.markdown(
    """
    - This application is designed for use in the **United States** and may not comply with the laws of other jurisdictions.
    - Laws regarding tenant-landlord disputes, contracts, and litigation vary significantly between states and localities. 
    - Users are strongly encouraged to consult with a licensed attorney familiar with the laws in their state or municipality before taking any action based on the information provided by this tool.
    """
)

# AI Limitation Disclaimer
st.header("🤖 AI Limitations Disclaimer")
st.markdown(
    """
    - The outputs generated by this application are based on patterns in the data and AI algorithms, and they may not always provide accurate or comprehensive results.
    - This tool does not replace professional legal judgment, and users are solely responsible for verifying the accuracy and applicability of any outputs.
    - The developers and providers of this application are not liable for any errors, omissions, or decisions made based on the outputs of this tool.
    """
)

# No Attorney-Client Relationship
st.header("🚫 No Attorney-Client Relationship")
st.markdown(
    """
    - The use of this application does not create an attorney-client relationship between the user and the developers, providers, or affiliates of this tool.
    - Any communications or information provided within this application are not protected by attorney-client privilege.
    """
)

# Liability Disclaimer
st.header("⚠️ Limitation of Liability")
st.markdown(
    """
    - The **developers and providers** of this application disclaim all liability for any damages, losses, or legal actions resulting from the use of this tool.
    - This application is provided on an "as-is" basis, with no warranties or guarantees regarding its performance, accuracy, or suitability for specific purposes.
    """
)

# User Responsibility
st.header("👤 User Responsibility")
st.markdown(
    """
    - Users of this application are responsible for ensuring compliance with all applicable laws and regulations.
    - The information and outputs generated by this tool should be used as a supplementary resource and not as a definitive guide.
    """
)

# Contact Information
st.header("📬 Contact Us")
st.markdown(
    """
    If you have any questions or concerns regarding this disclaimer or the application, please contact us at:
    - **Email**: [example@example.com](mailto:example@example.com)
    - **Phone**: +1 (555) 123-4567
    """
)

# Footer
st.markdown("---")
st.markdown(
    """
    🚨 **Disclaimer:** This application is not a substitute for legal advice. Always consult a qualified attorney for specific legal concerns.
    """
)
